name: Deploy via Rsync

on:
  push:
    branches:
      - main

jobs:
  rsync-task:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Sync File to VM as Root
        run: |
          echo "hello world ok done tested" > file.txt
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" file.txt ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/tmp/

      - name: Move File to Root Directory on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "sudo mv /tmp/file.txt /root/file.txt && sudo chmod 644 /root/file.txt"

      - name: Verify File on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cat /root/file.txt"