name: Push-triggered workflow

# This workflow will run when code is pushed to the repository
on:
  push:
    branches:
      - main  # Replace with your default branch name (e.g., master, main)

# A workflow run is made up of one or more jobs
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello, this workflow runs on push!"