name: Show Variable with Default

on:
  push:
    branches:
      - main

jobs:
  show-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Display the variable with default
        run: echo "The value of 'nametest' is:${{ secrets.my_secret || 'default_value' }}"