name: Access Secret Example

on:
  push:
    branches:
      - main

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Access secret
        run: echo "The secret value is ${{ secrets.nametest }}"