name: Show Variable Example

on:
  push:
    branches:
      - main

jobs:
  show-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Display the variable
        run: echo "The value of 'nametest' is: ${{ vars.nametest }}"